-- =============================================================================
-- V1 — Cadastros basicos do SRM Credit Engine
--
-- Tabelas de referencia: moedas, cedentes, tipos de recebivel, parametros de
-- precificacao, cotacoes de cambio e calendario de feriados.
-- O nucleo transacional (operacao, recebivel, liquidacao, auditoria) vem na V2.
--
-- Modelo completo e justificativas em docs/data-model.md.
--
-- Convencoes aplicadas aqui:
--
--   * Toda coluna numerica e' NUMERIC. Nunca real, double precision ou float:
--     precisao decimal e' criterio de avaliacao explicito, e ponto flutuante
--     no caminho do dinheiro e' indefensavel independentemente do erro.
--
--   * Constraints sao nomeadas, para que a violacao diga qual regra quebrou
--     em vez de um identificador gerado pelo banco.
--
--   * IDs usam GENERATED BY DEFAULT AS IDENTITY (SQL padrao) em vez de
--     BIGSERIAL. Estas tabelas sao dados de referencia, com volume baixo e
--     sem insercao em lote. IDENTITY impede batch de INSERT no Hibernate;
--     onde isso pesa e' no recebivel, e a decisao sera tomada na V2.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- moeda
-- -----------------------------------------------------------------------------
CREATE TABLE moeda (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo        CHAR(3)     NOT NULL,
    nome          VARCHAR(60) NOT NULL,
    escala_padrao SMALLINT    NOT NULL,

    CONSTRAINT uk_moeda_codigo UNIQUE (codigo),
    CONSTRAINT ck_moeda_codigo_iso CHECK (codigo ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_moeda_escala CHECK (escala_padrao BETWEEN 0 AND 4)
);

COMMENT ON TABLE moeda IS
    'Moedas suportadas, codigo ISO 4217.';
COMMENT ON COLUMN moeda.escala_padrao IS
    'Casas decimais da moeda, usada como escala de arredondamento. BRL e USD usam 2; JPY usa 0; KWD usa 3. Orientada a dado para nao hardcodar scale=2 no codigo.';


-- -----------------------------------------------------------------------------
-- cedente
-- -----------------------------------------------------------------------------
CREATE TABLE cedente (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento    VARCHAR(14)  NOT NULL,
    razao_social VARCHAR(200) NOT NULL,
    ativo        BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_cedente_documento UNIQUE (documento),
    CONSTRAINT ck_cedente_documento CHECK (documento ~ '^[0-9]{14}$')
);

COMMENT ON TABLE cedente IS
    'Empresa que cede o recebivel ao fundo em troca de liquidez.';
COMMENT ON COLUMN cedente.documento IS
    'CNPJ somente digitos. Formatacao e'' responsabilidade da camada de apresentacao.';
COMMENT ON COLUMN cedente.ativo IS
    'Cedente inativo nao origina operacao nova; operacoes antigas permanecem.';


-- -----------------------------------------------------------------------------
-- tipo_recebivel
-- -----------------------------------------------------------------------------
CREATE TABLE tipo_recebivel (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo             VARCHAR(40)  NOT NULL,
    nome               VARCHAR(80)  NOT NULL,
    spread             NUMERIC(9,6) NOT NULL,
    periodicidade      VARCHAR(10)  NOT NULL,
    convencao_contagem VARCHAR(20)  NOT NULL,
    ativo              BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_tipo_recebivel_codigo UNIQUE (codigo),
    CONSTRAINT ck_tipo_recebivel_spread CHECK (spread >= 0),
    CONSTRAINT ck_tipo_recebivel_periodicidade
        CHECK (periodicidade IN ('DIARIA', 'MENSAL', 'ANUAL')),
    CONSTRAINT ck_tipo_recebivel_convencao
        CHECK (convencao_contagem IN ('ACT_30', 'COMERCIAL_30_360', 'ACT_360',
                                      'ACT_365', 'TAXA_DIARIA', 'BUS_252'))
);

COMMENT ON TABLE tipo_recebivel IS
    'Produto adquirido pelo fundo. O codigo e'' a chave que resolve a Strategy de spread.';
COMMENT ON COLUMN tipo_recebivel.spread IS
    'Premio de risco. NUMERIC(9,6): 6 casas porque taxa entra em exponenciacao, e erro de arredondamento na taxa e'' amplificado pelo expoente. O valor mora aqui para ajuste sem deploy; a regra de derivacao mora na Strategy.';
COMMENT ON COLUMN tipo_recebivel.periodicidade IS
    'Unidade de capitalizacao do spread. Precisa casar com a unidade produzida pela convencao_contagem: combinar taxa mensal com base anual nao lanca erro, produz preco errado por ordem de grandeza.';


-- -----------------------------------------------------------------------------
-- parametro_precificacao  (append-only)
-- -----------------------------------------------------------------------------
CREATE TABLE parametro_precificacao (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxa_base       NUMERIC(9,6) NOT NULL,
    periodicidade   VARCHAR(10)  NOT NULL,
    vigencia_inicio TIMESTAMPTZ  NOT NULL,

    CONSTRAINT ck_parametro_taxa_base CHECK (taxa_base >= 0),
    CONSTRAINT ck_parametro_periodicidade
        CHECK (periodicidade IN ('DIARIA', 'MENSAL', 'ANUAL'))
);

CREATE INDEX ix_parametro_vigencia
    ON parametro_precificacao (vigencia_inicio DESC);

COMMENT ON TABLE parametro_precificacao IS
    'Taxa base do fundo, versionada por vigencia. APPEND-ONLY: nunca sofre UPDATE. A vigente para uma data e'' a mais recente com vigencia_inicio <= data. Se fosse mutavel, reprecificar uma operacao passada daria resultado diferente do contratado.';


-- -----------------------------------------------------------------------------
-- taxa_cambio  (append-only)
-- -----------------------------------------------------------------------------
CREATE TABLE taxa_cambio (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moeda_origem_id  BIGINT        NOT NULL,
    moeda_destino_id BIGINT        NOT NULL,
    cotacao          NUMERIC(19,6) NOT NULL,
    vigencia_inicio  TIMESTAMPTZ   NOT NULL,
    fonte            VARCHAR(20)   NOT NULL,

    CONSTRAINT fk_taxa_cambio_origem
        FOREIGN KEY (moeda_origem_id)  REFERENCES moeda (id),
    CONSTRAINT fk_taxa_cambio_destino
        FOREIGN KEY (moeda_destino_id) REFERENCES moeda (id),
    CONSTRAINT ck_taxa_cambio_cotacao CHECK (cotacao > 0),
    CONSTRAINT ck_taxa_cambio_par_distinto CHECK (moeda_origem_id <> moeda_destino_id),
    CONSTRAINT ck_taxa_cambio_fonte CHECK (fonte IN ('MANUAL', 'PROVEDOR'))
);

-- Serve a consulta "cotacao vigente na data". O DESC deixa a resposta na
-- primeira linha do indice, sem ordenacao adicional.
CREATE INDEX ix_taxa_cambio_par_vigencia
    ON taxa_cambio (moeda_origem_id, moeda_destino_id, vigencia_inicio DESC);

COMMENT ON TABLE taxa_cambio IS
    'Cotacoes por par de moedas, versionadas por vigencia. APPEND-ONLY: cotacao nunca e'' sobrescrita, para que a precificacao de ontem continue reproduzivel.';
COMMENT ON COLUMN taxa_cambio.cotacao IS
    'Unidades da moeda de destino por unidade da moeda de origem. NUMERIC(19,6): mercado cota com 4 a 6 casas (a PTAX usa 4).';
COMMENT ON COLUMN taxa_cambio.fonte IS
    'Distingue atualizacao manual de integracao com provedor externo.';


-- -----------------------------------------------------------------------------
-- feriado
-- -----------------------------------------------------------------------------
CREATE TABLE feriado (
    data        DATE        NOT NULL PRIMARY KEY,
    descricao   VARCHAR(80) NOT NULL,
    abrangencia VARCHAR(20) NOT NULL,

    CONSTRAINT ck_feriado_abrangencia CHECK (abrangencia IN ('NACIONAL'))
);

COMMENT ON TABLE feriado IS
    'Calendario de dias nao uteis, consumido pela convencao de contagem BUS_252. Cobertura limitada a feriados nacionais dos anos semeados; feriado municipal esta fora de escopo e a limitacao e'' declarada no README.';
