-- =============================================================================
-- V2 — Nucleo transacional do SRM Credit Engine
--
-- Operacao de cessao, recebiveis do lote, liquidacao e trilha de auditoria.
-- Depende das tabelas de cadastro da V1.
--
-- Modelo completo e justificativas em docs/data-model.md.
--
-- E' aqui que moram as garantias que o paragrafo 3.3 do enunciado cobra:
-- transacao ACID, nenhuma liquidacao pela metade, e protecao contra race
-- condition. Tres delas sao estruturais e vivem no banco:
--
--   1. operacao.version           -> optimistic locking (@Version do JPA)
--   2. UNIQUE (operacao_id)       -> impede liquidacao dupla mesmo se o
--                                    codigo falhar
--   3. UNIQUE (chave_idempotencia)-> retry do cliente nao duplica liquidacao
--
-- ESTRATEGIA DE ID — a decisao adiada na V1:
--
--   A V1 usou GENERATED BY DEFAULT AS IDENTITY porque tabelas de referencia
--   sao escritas uma linha por vez. Aqui a regra se aplica ao contrario onde
--   o padrao de escrita muda:
--
--     * recebivel e evento_auditoria sao escritos EM LOTE. IDENTITY forca o
--       Hibernate a desabilitar batch de INSERT, porque precisa do id gerado
--       a cada linha. Usam SEQUENCE com INCREMENT BY 50.
--     * operacao e liquidacao sao sempre uma linha por requisicao. Nao ha
--       lote para agrupar; IDENTITY e' mais simples e nao custa nada.
--
--   ATENCAO (PBI-11): o INCREMENT BY 50 das sequences precisa bater com o
--   allocationSize = 50 do @SequenceGenerator. Divergencia entre os dois
--   gera colisao de id — e' o erro classico dessa configuracao.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- operacao
-- -----------------------------------------------------------------------------
CREATE TABLE operacao (
    id                   BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedente_id           BIGINT        NOT NULL,
    moeda_titulo_id      BIGINT        NOT NULL,
    moeda_liquidacao_id  BIGINT        NOT NULL,
    taxa_cambio_id       BIGINT        NULL,
    valor_face_total     NUMERIC(19,2) NOT NULL,
    valor_presente_total NUMERIC(19,2) NOT NULL,
    valor_liquidacao     NUMERIC(19,2) NOT NULL,
    status               VARCHAR(15)   NOT NULL,
    version              BIGINT        NOT NULL DEFAULT 0,
    criado_em            TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_operacao_cedente
        FOREIGN KEY (cedente_id)          REFERENCES cedente (id),
    CONSTRAINT fk_operacao_moeda_titulo
        FOREIGN KEY (moeda_titulo_id)     REFERENCES moeda (id),
    CONSTRAINT fk_operacao_moeda_liquidacao
        FOREIGN KEY (moeda_liquidacao_id) REFERENCES moeda (id),
    CONSTRAINT fk_operacao_taxa_cambio
        FOREIGN KEY (taxa_cambio_id)      REFERENCES taxa_cambio (id),

    CONSTRAINT ck_operacao_status
        CHECK (status IN ('PENDENTE', 'LIQUIDADA', 'CANCELADA')),
    CONSTRAINT ck_operacao_valor_face CHECK (valor_face_total > 0),
    CONSTRAINT ck_operacao_valor_presente CHECK (valor_presente_total > 0),
    CONSTRAINT ck_operacao_valor_liquidacao CHECK (valor_liquidacao > 0),
    CONSTRAINT ck_operacao_desagio_nao_negativo
        CHECK (valor_presente_total <= valor_face_total),
    CONSTRAINT ck_operacao_version CHECK (version >= 0),

    -- Cross-currency exige cotacao; moeda unica proibe. As duas direcoes,
    -- para nao existir operacao com cambio faltando nem com cambio sobrando.
    CONSTRAINT ck_operacao_cambio_coerente CHECK (
        (moeda_titulo_id =  moeda_liquidacao_id AND taxa_cambio_id IS NULL)
     OR (moeda_titulo_id <> moeda_liquidacao_id AND taxa_cambio_id IS NOT NULL)
    )
);

-- Filtro do Extrato de Liquidacao (PBI-35): periodo por cedente.
CREATE INDEX ix_operacao_cedente_criado ON operacao (cedente_id, criado_em);

COMMENT ON TABLE operacao IS
    'Cessao de um lote de recebiveis por um cedente. Unidade de negocio e de transacao: ou o lote inteiro entra, ou nada entra.';
COMMENT ON COLUMN operacao.version IS
    'Optimistic locking. Duas liquidacoes concorrentes: uma vence, a outra falha com conflito de versao e recebe 409.';
COMMENT ON COLUMN operacao.valor_liquidacao IS
    'Valor presente apos a conversao cambial, na moeda de liquidacao. Igual a valor_presente_total quando a operacao e'' em moeda unica.';


-- -----------------------------------------------------------------------------
-- recebivel
-- -----------------------------------------------------------------------------
CREATE SEQUENCE seq_recebivel INCREMENT BY 50;

CREATE TABLE recebivel (
    id                         BIGINT        NOT NULL DEFAULT nextval('seq_recebivel') PRIMARY KEY,
    operacao_id                BIGINT        NOT NULL,
    tipo_recebivel_id          BIGINT        NOT NULL,
    parametro_precificacao_id  BIGINT        NOT NULL,
    numero_documento           VARCHAR(50)   NOT NULL,
    sacado_documento           VARCHAR(14)   NOT NULL,
    valor_face                 NUMERIC(19,2) NOT NULL,
    data_vencimento            DATE          NOT NULL,
    convencao_aplicada         VARCHAR(20)   NOT NULL,
    expoente_aplicado          NUMERIC(19,10) NOT NULL,
    taxa_base_aplicada         NUMERIC(9,6)  NOT NULL,
    spread_aplicado            NUMERIC(9,6)  NOT NULL,
    valor_presente             NUMERIC(19,2) NOT NULL,

    -- Recebivel nao existe fora do lote: composicao, nao associacao.
    CONSTRAINT fk_recebivel_operacao
        FOREIGN KEY (operacao_id) REFERENCES operacao (id) ON DELETE CASCADE,
    CONSTRAINT fk_recebivel_tipo
        FOREIGN KEY (tipo_recebivel_id) REFERENCES tipo_recebivel (id),
    CONSTRAINT fk_recebivel_parametro
        FOREIGN KEY (parametro_precificacao_id) REFERENCES parametro_precificacao (id),

    CONSTRAINT ck_recebivel_valor_face CHECK (valor_face > 0),
    CONSTRAINT ck_recebivel_valor_presente CHECK (valor_presente > 0),
    CONSTRAINT ck_recebivel_desagio_nao_negativo
        CHECK (valor_presente <= valor_face),
    CONSTRAINT ck_recebivel_expoente CHECK (expoente_aplicado >= 0),
    CONSTRAINT ck_recebivel_taxa_base CHECK (taxa_base_aplicada >= 0),
    CONSTRAINT ck_recebivel_spread CHECK (spread_aplicado >= 0),
    CONSTRAINT ck_recebivel_convencao
        CHECK (convencao_aplicada IN ('ACT_30', 'COMERCIAL_30_360', 'ACT_360',
                                      'ACT_365', 'TAXA_DIARIA', 'BUS_252'))
);

ALTER SEQUENCE seq_recebivel OWNED BY recebivel.id;

-- O Postgres nao indexa chave estrangeira automaticamente, so PRIMARY KEY e
-- UNIQUE. Este indice existe porque buscar os recebiveis de uma operacao e' a
-- leitura mais frequente do agregado. As demais FKs apontam para tabelas de
-- cadastro pequenas e nunca deletadas: indice ali seria custo sem retorno.
CREATE INDEX ix_recebivel_operacao ON recebivel (operacao_id);

COMMENT ON TABLE recebivel IS
    'Titulo individual dentro do lote, precificado com os parametros congelados no momento da operacao.';
COMMENT ON COLUMN recebivel.expoente_aplicado IS
    'Expoente usado na formula, ja normalizado pela convencao de contagem. Congelado porque o mesmo intervalo de datas produz expoentes diferentes conforme a convencao — prazo em meses nao seria representacao suficiente.';
COMMENT ON COLUMN recebivel.taxa_base_aplicada IS
    'Valor congelado. A FK parametro_precificacao_id da a linhagem (qual registro foi usado); esta coluna da a imutabilidade (quanto ele valia). Auditoria precisa das duas respostas.';


-- -----------------------------------------------------------------------------
-- liquidacao
-- -----------------------------------------------------------------------------
CREATE TABLE liquidacao (
    id                 BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operacao_id        BIGINT        NOT NULL,
    chave_idempotencia VARCHAR(64)   NOT NULL,
    valor_liquidado    NUMERIC(19,2) NOT NULL,
    cotacao_aplicada   NUMERIC(19,6) NULL,
    liquidado_em       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    liquidado_por      VARCHAR(80)   NOT NULL,

    CONSTRAINT fk_liquidacao_operacao
        FOREIGN KEY (operacao_id) REFERENCES operacao (id),

    -- A garantia de que nao existe liquidacao dupla e' do banco, nao do codigo.
    -- Mesmo com falha na camada de negocio, a segunda insercao e' recusada.
    CONSTRAINT uk_liquidacao_operacao UNIQUE (operacao_id),
    CONSTRAINT uk_liquidacao_idempotencia UNIQUE (chave_idempotencia),

    CONSTRAINT ck_liquidacao_valor CHECK (valor_liquidado > 0),
    CONSTRAINT ck_liquidacao_cotacao CHECK (cotacao_aplicada IS NULL OR cotacao_aplicada > 0)
);

-- Filtro de periodo do Extrato de Liquidacao (PBI-35).
CREATE INDEX ix_liquidacao_liquidado_em ON liquidacao (liquidado_em);

COMMENT ON TABLE liquidacao IS
    'Efetivacao financeira da operacao. Irreversivel e unica: o UNIQUE em operacao_id e'' a terceira linha de defesa contra liquidacao dupla, junto com o optimistic locking e a chave de idempotencia.';
COMMENT ON COLUMN liquidacao.chave_idempotencia IS
    'Retry do cliente com a mesma chave devolve o resultado original em vez de liquidar de novo.';


-- -----------------------------------------------------------------------------
-- evento_auditoria  (append-only, garantido por trigger)
-- -----------------------------------------------------------------------------
CREATE SEQUENCE seq_evento_auditoria INCREMENT BY 50;

CREATE TABLE evento_auditoria (
    id          BIGINT      NOT NULL DEFAULT nextval('seq_evento_auditoria') PRIMARY KEY,
    entidade    VARCHAR(40) NOT NULL,
    entidade_id BIGINT      NOT NULL,
    tipo_evento VARCHAR(40) NOT NULL,
    payload     JSONB       NOT NULL,
    ocorrido_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    ator        VARCHAR(80) NOT NULL,

    CONSTRAINT ck_evento_entidade CHECK (entidade IN ('OPERACAO', 'LIQUIDACAO'))
);

ALTER SEQUENCE seq_evento_auditoria OWNED BY evento_auditoria.id;

CREATE INDEX ix_evento_entidade ON evento_auditoria (entidade, entidade_id);

-- Trilha que pode ser alterada nao e' trilha. O trigger transforma a regra
-- append-only em garantia estrutural, em vez de convencao documentada.
--
-- Em producao a resposta melhor seria REVOKE UPDATE, DELETE para o papel da
-- aplicacao; aqui a aplicacao conecta como superusuario, que ignora GRANT,
-- entao o trigger e' o que efetivamente segura.
CREATE OR REPLACE FUNCTION fn_evento_auditoria_imutavel()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'evento_auditoria e append-only: % nao e permitido', TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_evento_auditoria_imutavel
    BEFORE UPDATE OR DELETE ON evento_auditoria
    FOR EACH ROW EXECUTE FUNCTION fn_evento_auditoria_imutavel();

COMMENT ON TABLE evento_auditoria IS
    'Trilha append-only. Referencia polimorfica (entidade + entidade_id) em vez de FK: perde integridade declarativa, ganha uma trilha unica em vez de uma tabela de auditoria por tabela auditada. Para registro, e nao navegacao, a troca compensa.';
