-- =============================================================================
-- SRM Credit Engine — DDL consolidado
--
-- Atende ao paragrafo 7.2 do enunciado, que pede os scripts SQL de criacao da
-- estrutura em /docs, independentemente da ferramenta de migracao usada.
--
-- ARQUIVO GERADO. NAO EDITAR.
--
--   A fonte da verdade e' o Flyway, em apps/api/src/main/resources/db/migration.
--   Alterar este arquivo nao muda banco nenhum: o schema real vem das
--   migracoes, e o Hibernate roda com ddl-auto=validate apenas conferindo.
--
--   Ao adicionar uma migracao, regenere com:
--
--     docker compose up -d db
--     cd apps/api && ./mvnw test          # aplica as migracoes
--     docker exec credit-engine-db pg_dump -U postgres -d credit-engine \
--       --schema-only --no-owner --no-privileges \
--       --exclude-table=flyway_schema_history > /tmp/dump.sql
--     # prefixe este cabecalho ao resultado
--
-- O QUE FOI EXCLUIDO E POR QUE
--
--   * flyway_schema_history — tabela de controle do proprio Flyway, criada
--     automaticamente. Nao faz parte da estrutura do dominio.
--   * OWNER e GRANT — o papel do banco varia por ambiente; incluir amarraria o
--     script ao usuario local.
--
-- O QUE ESTA INCLUIDO
--
--   Tabelas, sequences, chaves primarias e estrangeiras, constraints UNIQUE e
--   CHECK, indices, defaults, o trigger que torna a trilha de auditoria
--   append-only, e os COMMENT que carregam o dicionario de dados para dentro
--   do banco.
--
--   Modelo comentado, com as justificativas de precisao e escala:
--   docs/data-model.md
--
-- REPRODUTIBILIDADE — verificado, com uma ressalva honesta
--
--   Aplicar este arquivo num banco vazio produz um schema SEMANTICAMENTE
--   identico ao construido pelo Flyway. Comparado item a item:
--
--     66 colunas (tipo, nulidade, precisao, escala, default) ... identicas
--     54 constraints (10 PK, 10 FK, 5 UNIQUE, 29 CHECK) .......... identicas
--     21 indices ................................................ identicos
--      9 sequences (nome e increment_by) ........................ identicas
--      1 trigger ................................................ identico
--
--   O diff textual dos dois pg_dump mostra 14 linhas diferentes, TODAS do
--   mesmo padrao: o Postgres reimprime predicados IN (...) ora como
--
--     x = ANY ((ARRAY['A'::varchar, 'B'::varchar])::text[])
--
--   ora como
--
--     x = ANY (ARRAY[('A'::varchar)::text, ('B'::varchar)::text])
--
--   As duas formas sao equivalentes — muda so onde o cast para text[] e'
--   aplicado. E' artefato de round-trip do proprio pg_dump, nao divergencia
--   de schema.
-- =============================================================================
--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: fn_evento_auditoria_imutavel(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_evento_auditoria_imutavel() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    RAISE EXCEPTION 'evento_auditoria e append-only: % nao e permitido', TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cedente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cedente (
    id bigint NOT NULL,
    documento character varying(14) NOT NULL,
    razao_social character varying(200) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    CONSTRAINT ck_cedente_documento CHECK (((documento)::text ~ '^[0-9]{14}$'::text))
);


--
-- Name: TABLE cedente; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.cedente IS 'Empresa que cede o recebivel ao fundo em troca de liquidez.';


--
-- Name: COLUMN cedente.documento; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.cedente.documento IS 'CNPJ somente digitos. Formatacao e'' responsabilidade da camada de apresentacao.';


--
-- Name: COLUMN cedente.ativo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.cedente.ativo IS 'Cedente inativo nao origina operacao nova; operacoes antigas permanecem.';


--
-- Name: cedente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cedente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cedente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evento_auditoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evento_auditoria (
    id bigint NOT NULL,
    entidade character varying(40) NOT NULL,
    entidade_id bigint NOT NULL,
    tipo_evento character varying(40) NOT NULL,
    payload jsonb NOT NULL,
    ocorrido_em timestamp with time zone DEFAULT now() NOT NULL,
    ator character varying(80) NOT NULL,
    CONSTRAINT ck_evento_entidade CHECK (((entidade)::text = ANY ((ARRAY['OPERACAO'::character varying, 'LIQUIDACAO'::character varying])::text[])))
);


--
-- Name: TABLE evento_auditoria; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.evento_auditoria IS 'Trilha append-only. Referencia polimorfica (entidade + entidade_id) em vez de FK: perde integridade declarativa, ganha uma trilha unica em vez de uma tabela de auditoria por tabela auditada. Para registro, e nao navegacao, a troca compensa.';


--
-- Name: feriado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feriado (
    data date NOT NULL,
    descricao character varying(80) NOT NULL,
    abrangencia character varying(20) NOT NULL,
    CONSTRAINT ck_feriado_abrangencia CHECK (((abrangencia)::text = 'NACIONAL'::text))
);


--
-- Name: TABLE feriado; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.feriado IS 'Calendario de dias nao uteis, consumido pela convencao de contagem BUS_252. Cobertura limitada a feriados nacionais dos anos semeados; feriado municipal esta fora de escopo e a limitacao e'' declarada no README.';


--
-- Name: liquidacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.liquidacao (
    id bigint NOT NULL,
    operacao_id bigint NOT NULL,
    chave_idempotencia character varying(64) NOT NULL,
    valor_liquidado numeric(19,2) NOT NULL,
    cotacao_aplicada numeric(19,6),
    liquidado_em timestamp with time zone DEFAULT now() NOT NULL,
    liquidado_por character varying(80) NOT NULL,
    CONSTRAINT ck_liquidacao_cotacao CHECK (((cotacao_aplicada IS NULL) OR (cotacao_aplicada > (0)::numeric))),
    CONSTRAINT ck_liquidacao_valor CHECK ((valor_liquidado > (0)::numeric))
);


--
-- Name: TABLE liquidacao; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.liquidacao IS 'Efetivacao financeira da operacao. Irreversivel e unica: o UNIQUE em operacao_id e'' a terceira linha de defesa contra liquidacao dupla, junto com o optimistic locking e a chave de idempotencia.';


--
-- Name: COLUMN liquidacao.chave_idempotencia; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.liquidacao.chave_idempotencia IS 'Retry do cliente com a mesma chave devolve o resultado original em vez de liquidar de novo.';


--
-- Name: liquidacao_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.liquidacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.liquidacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: moeda; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.moeda (
    id bigint NOT NULL,
    codigo character(3) NOT NULL,
    nome character varying(60) NOT NULL,
    escala_padrao smallint NOT NULL,
    CONSTRAINT ck_moeda_codigo_iso CHECK ((codigo ~ '^[A-Z]{3}$'::text)),
    CONSTRAINT ck_moeda_escala CHECK (((escala_padrao >= 0) AND (escala_padrao <= 4)))
);


--
-- Name: TABLE moeda; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.moeda IS 'Moedas suportadas, codigo ISO 4217.';


--
-- Name: COLUMN moeda.escala_padrao; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.moeda.escala_padrao IS 'Casas decimais da moeda, usada como escala de arredondamento. BRL e USD usam 2; JPY usa 0; KWD usa 3. Orientada a dado para nao hardcodar scale=2 no codigo.';


--
-- Name: moeda_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.moeda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.moeda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: operacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.operacao (
    id bigint NOT NULL,
    cedente_id bigint NOT NULL,
    moeda_titulo_id bigint NOT NULL,
    moeda_liquidacao_id bigint NOT NULL,
    taxa_cambio_id bigint,
    valor_face_total numeric(19,2) NOT NULL,
    valor_presente_total numeric(19,2) NOT NULL,
    valor_liquidacao numeric(19,2) NOT NULL,
    status character varying(15) NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_operacao_cambio_coerente CHECK ((((moeda_titulo_id = moeda_liquidacao_id) AND (taxa_cambio_id IS NULL)) OR ((moeda_titulo_id <> moeda_liquidacao_id) AND (taxa_cambio_id IS NOT NULL)))),
    CONSTRAINT ck_operacao_desagio_nao_negativo CHECK ((valor_presente_total <= valor_face_total)),
    CONSTRAINT ck_operacao_status CHECK (((status)::text = ANY ((ARRAY['PENDENTE'::character varying, 'LIQUIDADA'::character varying, 'CANCELADA'::character varying])::text[]))),
    CONSTRAINT ck_operacao_valor_face CHECK ((valor_face_total > (0)::numeric)),
    CONSTRAINT ck_operacao_valor_liquidacao CHECK ((valor_liquidacao > (0)::numeric)),
    CONSTRAINT ck_operacao_valor_presente CHECK ((valor_presente_total > (0)::numeric)),
    CONSTRAINT ck_operacao_version CHECK ((version >= 0))
);


--
-- Name: TABLE operacao; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.operacao IS 'Cessao de um lote de recebiveis por um cedente. Unidade de negocio e de transacao: ou o lote inteiro entra, ou nada entra.';


--
-- Name: COLUMN operacao.valor_liquidacao; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.operacao.valor_liquidacao IS 'Valor presente apos a conversao cambial, na moeda de liquidacao. Igual a valor_presente_total quando a operacao e'' em moeda unica.';


--
-- Name: COLUMN operacao.version; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.operacao.version IS 'Optimistic locking. Duas liquidacoes concorrentes: uma vence, a outra falha com conflito de versao e recebe 409.';


--
-- Name: operacao_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.operacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parametro_precificacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parametro_precificacao (
    id bigint NOT NULL,
    taxa_base numeric(9,6) NOT NULL,
    periodicidade character varying(10) NOT NULL,
    vigencia_inicio timestamp with time zone NOT NULL,
    CONSTRAINT ck_parametro_periodicidade CHECK (((periodicidade)::text = ANY ((ARRAY['DIARIA'::character varying, 'MENSAL'::character varying, 'ANUAL'::character varying])::text[]))),
    CONSTRAINT ck_parametro_taxa_base CHECK ((taxa_base >= (0)::numeric))
);


--
-- Name: TABLE parametro_precificacao; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.parametro_precificacao IS 'Taxa base do fundo, versionada por vigencia. APPEND-ONLY: nunca sofre UPDATE. A vigente para uma data e'' a mais recente com vigencia_inicio <= data. Se fosse mutavel, reprecificar uma operacao passada daria resultado diferente do contratado.';


--
-- Name: parametro_precificacao_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.parametro_precificacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parametro_precificacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recebivel; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recebivel (
    id bigint NOT NULL,
    operacao_id bigint NOT NULL,
    tipo_recebivel_id bigint NOT NULL,
    parametro_precificacao_id bigint NOT NULL,
    numero_documento character varying(50) NOT NULL,
    sacado_documento character varying(14) NOT NULL,
    valor_face numeric(19,2) NOT NULL,
    data_vencimento date NOT NULL,
    convencao_aplicada character varying(20) NOT NULL,
    expoente_aplicado numeric(19,10) NOT NULL,
    taxa_base_aplicada numeric(9,6) NOT NULL,
    spread_aplicado numeric(9,6) NOT NULL,
    valor_presente numeric(19,2) NOT NULL,
    CONSTRAINT ck_recebivel_convencao CHECK (((convencao_aplicada)::text = ANY ((ARRAY['ACT_30'::character varying, 'COMERCIAL_30_360'::character varying, 'ACT_360'::character varying, 'ACT_365'::character varying, 'TAXA_DIARIA'::character varying, 'BUS_252'::character varying])::text[]))),
    CONSTRAINT ck_recebivel_desagio_nao_negativo CHECK ((valor_presente <= valor_face)),
    CONSTRAINT ck_recebivel_expoente CHECK ((expoente_aplicado >= (0)::numeric)),
    CONSTRAINT ck_recebivel_spread CHECK ((spread_aplicado >= (0)::numeric)),
    CONSTRAINT ck_recebivel_taxa_base CHECK ((taxa_base_aplicada >= (0)::numeric)),
    CONSTRAINT ck_recebivel_valor_face CHECK ((valor_face > (0)::numeric)),
    CONSTRAINT ck_recebivel_valor_presente CHECK ((valor_presente > (0)::numeric))
);


--
-- Name: TABLE recebivel; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.recebivel IS 'Titulo individual dentro do lote, precificado com os parametros congelados no momento da operacao.';


--
-- Name: COLUMN recebivel.expoente_aplicado; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.recebivel.expoente_aplicado IS 'Expoente usado na formula, ja normalizado pela convencao de contagem. Congelado porque o mesmo intervalo de datas produz expoentes diferentes conforme a convencao — prazo em meses nao seria representacao suficiente.';


--
-- Name: COLUMN recebivel.taxa_base_aplicada; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.recebivel.taxa_base_aplicada IS 'Valor congelado. A FK parametro_precificacao_id da a linhagem (qual registro foi usado); esta coluna da a imutabilidade (quanto ele valia). Auditoria precisa das duas respostas.';


--
-- Name: seq_evento_auditoria; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seq_evento_auditoria
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: seq_evento_auditoria; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.seq_evento_auditoria OWNED BY public.evento_auditoria.id;


--
-- Name: seq_recebivel; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seq_recebivel
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: seq_recebivel; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.seq_recebivel OWNED BY public.recebivel.id;


--
-- Name: taxa_cambio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.taxa_cambio (
    id bigint NOT NULL,
    moeda_origem_id bigint NOT NULL,
    moeda_destino_id bigint NOT NULL,
    cotacao numeric(19,6) NOT NULL,
    vigencia_inicio timestamp with time zone NOT NULL,
    fonte character varying(20) NOT NULL,
    CONSTRAINT ck_taxa_cambio_cotacao CHECK ((cotacao > (0)::numeric)),
    CONSTRAINT ck_taxa_cambio_fonte CHECK (((fonte)::text = ANY ((ARRAY['MANUAL'::character varying, 'PROVEDOR'::character varying])::text[]))),
    CONSTRAINT ck_taxa_cambio_par_distinto CHECK ((moeda_origem_id <> moeda_destino_id))
);


--
-- Name: TABLE taxa_cambio; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.taxa_cambio IS 'Cotacoes por par de moedas, versionadas por vigencia. APPEND-ONLY: cotacao nunca e'' sobrescrita, para que a precificacao de ontem continue reproduzivel.';


--
-- Name: COLUMN taxa_cambio.cotacao; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.taxa_cambio.cotacao IS 'Unidades da moeda de destino por unidade da moeda de origem. NUMERIC(19,6): mercado cota com 4 a 6 casas (a PTAX usa 4).';


--
-- Name: COLUMN taxa_cambio.fonte; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.taxa_cambio.fonte IS 'Distingue atualizacao manual de integracao com provedor externo.';


--
-- Name: taxa_cambio_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.taxa_cambio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.taxa_cambio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_recebivel; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tipo_recebivel (
    id bigint NOT NULL,
    codigo character varying(40) NOT NULL,
    nome character varying(80) NOT NULL,
    spread numeric(9,6) NOT NULL,
    periodicidade character varying(10) NOT NULL,
    convencao_contagem character varying(20) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    CONSTRAINT ck_tipo_recebivel_convencao CHECK (((convencao_contagem)::text = ANY ((ARRAY['ACT_30'::character varying, 'COMERCIAL_30_360'::character varying, 'ACT_360'::character varying, 'ACT_365'::character varying, 'TAXA_DIARIA'::character varying, 'BUS_252'::character varying])::text[]))),
    CONSTRAINT ck_tipo_recebivel_periodicidade CHECK (((periodicidade)::text = ANY ((ARRAY['DIARIA'::character varying, 'MENSAL'::character varying, 'ANUAL'::character varying])::text[]))),
    CONSTRAINT ck_tipo_recebivel_spread CHECK ((spread >= (0)::numeric))
);


--
-- Name: TABLE tipo_recebivel; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.tipo_recebivel IS 'Produto adquirido pelo fundo. O codigo e'' a chave que resolve a Strategy de spread.';


--
-- Name: COLUMN tipo_recebivel.spread; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tipo_recebivel.spread IS 'Premio de risco. NUMERIC(9,6): 6 casas porque taxa entra em exponenciacao, e erro de arredondamento na taxa e'' amplificado pelo expoente. O valor mora aqui para ajuste sem deploy; a regra de derivacao mora na Strategy.';


--
-- Name: COLUMN tipo_recebivel.periodicidade; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tipo_recebivel.periodicidade IS 'Unidade de capitalizacao do spread. Precisa casar com a unidade produzida pela convencao_contagem: combinar taxa mensal com base anual nao lanca erro, produz preco errado por ordem de grandeza.';


--
-- Name: tipo_recebivel_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tipo_recebivel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_recebivel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evento_auditoria id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evento_auditoria ALTER COLUMN id SET DEFAULT nextval('public.seq_evento_auditoria'::regclass);


--
-- Name: recebivel id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebivel ALTER COLUMN id SET DEFAULT nextval('public.seq_recebivel'::regclass);


--
-- Name: cedente cedente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cedente
    ADD CONSTRAINT cedente_pkey PRIMARY KEY (id);


--
-- Name: evento_auditoria evento_auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evento_auditoria
    ADD CONSTRAINT evento_auditoria_pkey PRIMARY KEY (id);


--
-- Name: feriado feriado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feriado
    ADD CONSTRAINT feriado_pkey PRIMARY KEY (data);


--
-- Name: liquidacao liquidacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidacao
    ADD CONSTRAINT liquidacao_pkey PRIMARY KEY (id);


--
-- Name: moeda moeda_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.moeda
    ADD CONSTRAINT moeda_pkey PRIMARY KEY (id);


--
-- Name: operacao operacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operacao
    ADD CONSTRAINT operacao_pkey PRIMARY KEY (id);


--
-- Name: parametro_precificacao parametro_precificacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parametro_precificacao
    ADD CONSTRAINT parametro_precificacao_pkey PRIMARY KEY (id);


--
-- Name: recebivel recebivel_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebivel
    ADD CONSTRAINT recebivel_pkey PRIMARY KEY (id);


--
-- Name: taxa_cambio taxa_cambio_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.taxa_cambio
    ADD CONSTRAINT taxa_cambio_pkey PRIMARY KEY (id);


--
-- Name: tipo_recebivel tipo_recebivel_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipo_recebivel
    ADD CONSTRAINT tipo_recebivel_pkey PRIMARY KEY (id);


--
-- Name: cedente uk_cedente_documento; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cedente
    ADD CONSTRAINT uk_cedente_documento UNIQUE (documento);


--
-- Name: liquidacao uk_liquidacao_idempotencia; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidacao
    ADD CONSTRAINT uk_liquidacao_idempotencia UNIQUE (chave_idempotencia);


--
-- Name: liquidacao uk_liquidacao_operacao; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidacao
    ADD CONSTRAINT uk_liquidacao_operacao UNIQUE (operacao_id);


--
-- Name: moeda uk_moeda_codigo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.moeda
    ADD CONSTRAINT uk_moeda_codigo UNIQUE (codigo);


--
-- Name: tipo_recebivel uk_tipo_recebivel_codigo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipo_recebivel
    ADD CONSTRAINT uk_tipo_recebivel_codigo UNIQUE (codigo);


--
-- Name: ix_evento_entidade; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_evento_entidade ON public.evento_auditoria USING btree (entidade, entidade_id);


--
-- Name: ix_liquidacao_liquidado_em; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_liquidacao_liquidado_em ON public.liquidacao USING btree (liquidado_em);


--
-- Name: ix_liquidacao_valor_desc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_liquidacao_valor_desc ON public.liquidacao USING btree (valor_liquidado DESC, id DESC);


--
-- Name: INDEX ix_liquidacao_valor_desc; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON INDEX public.ix_liquidacao_valor_desc IS 'Ordenacao por valor no Extrato de Liquidacao sem filtro seletivo. Sem ele, LIMIT 20 sobre 100 mil linhas faz Parallel Seq Scan (~45 ms). Ver docs/performance.md.';


--
-- Name: ix_operacao_cedente_criado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_operacao_cedente_criado ON public.operacao USING btree (cedente_id, criado_em);


--
-- Name: ix_parametro_vigencia; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_parametro_vigencia ON public.parametro_precificacao USING btree (vigencia_inicio DESC);


--
-- Name: ix_recebivel_operacao; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_recebivel_operacao ON public.recebivel USING btree (operacao_id);


--
-- Name: ix_taxa_cambio_par_vigencia; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_taxa_cambio_par_vigencia ON public.taxa_cambio USING btree (moeda_origem_id, moeda_destino_id, vigencia_inicio DESC);


--
-- Name: evento_auditoria tg_evento_auditoria_imutavel; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER tg_evento_auditoria_imutavel BEFORE DELETE OR UPDATE ON public.evento_auditoria FOR EACH ROW EXECUTE FUNCTION public.fn_evento_auditoria_imutavel();


--
-- Name: liquidacao fk_liquidacao_operacao; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidacao
    ADD CONSTRAINT fk_liquidacao_operacao FOREIGN KEY (operacao_id) REFERENCES public.operacao(id);


--
-- Name: operacao fk_operacao_cedente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operacao
    ADD CONSTRAINT fk_operacao_cedente FOREIGN KEY (cedente_id) REFERENCES public.cedente(id);


--
-- Name: operacao fk_operacao_moeda_liquidacao; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operacao
    ADD CONSTRAINT fk_operacao_moeda_liquidacao FOREIGN KEY (moeda_liquidacao_id) REFERENCES public.moeda(id);


--
-- Name: operacao fk_operacao_moeda_titulo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operacao
    ADD CONSTRAINT fk_operacao_moeda_titulo FOREIGN KEY (moeda_titulo_id) REFERENCES public.moeda(id);


--
-- Name: operacao fk_operacao_taxa_cambio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operacao
    ADD CONSTRAINT fk_operacao_taxa_cambio FOREIGN KEY (taxa_cambio_id) REFERENCES public.taxa_cambio(id);


--
-- Name: recebivel fk_recebivel_operacao; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebivel
    ADD CONSTRAINT fk_recebivel_operacao FOREIGN KEY (operacao_id) REFERENCES public.operacao(id) ON DELETE CASCADE;


--
-- Name: recebivel fk_recebivel_parametro; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebivel
    ADD CONSTRAINT fk_recebivel_parametro FOREIGN KEY (parametro_precificacao_id) REFERENCES public.parametro_precificacao(id);


--
-- Name: recebivel fk_recebivel_tipo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recebivel
    ADD CONSTRAINT fk_recebivel_tipo FOREIGN KEY (tipo_recebivel_id) REFERENCES public.tipo_recebivel(id);


--
-- Name: taxa_cambio fk_taxa_cambio_destino; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.taxa_cambio
    ADD CONSTRAINT fk_taxa_cambio_destino FOREIGN KEY (moeda_destino_id) REFERENCES public.moeda(id);


--
-- Name: taxa_cambio fk_taxa_cambio_origem; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.taxa_cambio
    ADD CONSTRAINT fk_taxa_cambio_origem FOREIGN KEY (moeda_origem_id) REFERENCES public.moeda(id);


--
-- PostgreSQL database dump complete
--

